apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: si-msa
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_USER: "siuser"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: si-msa
type: Opaque
stringData:
  DB_PASSWORD: "change-me"
  JWT_SECRET: "change-this-to-a-very-long-secret-key-at-least-32-bytes!!"
