-- ===== 사용자 =====
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id    VARCHAR(50)  NOT NULL UNIQUE,
    password    VARCHAR(200),
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(200),
    phone       VARCHAR(30),
    role        VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at  TIMESTAMP,
    created_by  VARCHAR(50),
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(50)
);

-- ===== RBAC =====
CREATE TABLE roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    descr     VARCHAR(200)
);
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);
CREATE TABLE resources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_pattern VARCHAR(200) NOT NULL,
    http_method VARCHAR(10)  NOT NULL DEFAULT 'ALL',
    descr       VARCHAR(200),
    sort_order  INT DEFAULT 0,
    created_at  TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50)
);
CREATE TABLE role_resources (
    role_id     BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, resource_id)
);
CREATE TABLE menus (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  BIGINT,
    name       VARCHAR(100) NOT NULL,
    url        VARCHAR(200),
    icon       VARCHAR(50),
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50)
);
CREATE TABLE role_menus (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

-- ===== TokenStore(jdbc) 용 (type=jdbc 일 때 사용; 기본 memory 면 미사용) =====
CREATE TABLE refresh_tokens (
    token      VARCHAR(200) PRIMARY KEY,
    user_id    VARCHAR(100) NOT NULL,
    roles      VARCHAR(500),
    expires_at TIMESTAMP    NOT NULL
);
CREATE INDEX idx_refresh_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_exp  ON refresh_tokens(expires_at);
CREATE TABLE token_blacklist (
    jti        VARCHAR(100) PRIMARY KEY,
    expires_at TIMESTAMP    NOT NULL
);

-- ===== 필수 참조데이터: 역할 =====
INSERT INTO roles (id, role_name, descr) VALUES (1, 'ROLE_ADMIN', '관리자');
INSERT INTO roles (id, role_name, descr) VALUES (2, 'ROLE_USER',  '일반사용자');
