CREATE TABLE common_code (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code  VARCHAR(50)  NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    code_name   VARCHAR(200) NOT NULL,
    code_value  VARCHAR(200),
    sort_order  INT DEFAULT 0,
    use_yn      BOOLEAN NOT NULL DEFAULT TRUE,
    attr1       VARCHAR(200),
    attr2       VARCHAR(200),
    created_at  TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50),
    CONSTRAINT uq_common_code UNIQUE (group_code, code)
);
CREATE INDEX idx_common_code_group ON common_code(group_code);

-- 참조 코드 (운영에서도 필요한 기본 코드)
INSERT INTO common_code (group_code, code, code_name, sort_order) VALUES ('GENDER', 'M', '남성', 1);
INSERT INTO common_code (group_code, code, code_name, sort_order) VALUES ('GENDER', 'F', '여성', 2);
INSERT INTO common_code (group_code, code, code_name, sort_order) VALUES ('USE_YN', 'Y', '사용', 1);
INSERT INTO common_code (group_code, code, code_name, sort_order) VALUES ('USE_YN', 'N', '미사용', 2);
