CREATE TABLE file_metadata (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    stored_path   VARCHAR(500) NOT NULL,
    content_type  VARCHAR(150),
    size          BIGINT NOT NULL,
    storage_type  VARCHAR(20)  NOT NULL,   -- local | nas | s3
    created_at    TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50)
);
CREATE INDEX idx_file_created_at ON file_metadata(created_at);
