-- =====================================================================
-- 감사/접속 로그 테이블. framework.audit.store.type=jdbc 일 때 필요.
-- framework-audit 의 db/audit-log-postgres.sql 을 Flyway 마이그레이션으로 옮기되,
-- BIGSERIAL → "GENERATED BY DEFAULT AS IDENTITY" 로 바꿔 H2(PostgreSQL MODE)와
-- PostgreSQL 양쪽에서 동일하게 동작하도록 한다(로컬 H2 검증 + 운영 PG 동시 지원).
--
-- JdbcAuditEventSink 가 INSERT 하는 컬럼과 1:1 로 맞춰야 한다.
-- 보존기간(예: 1년)은 운영 정책에 맞춰 파티셔닝/아카이브 권장.
-- =====================================================================
CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time  TIMESTAMP    NOT NULL,
    event_type  VARCHAR(40)  NOT NULL,     -- METHOD_AUDIT | LOGIN_SUCCESS | LOGIN_FAILURE | LOGOUT
    actor       VARCHAR(100),              -- 행위자(사용자 ID), 미인증은 anonymous
    action      VARCHAR(100),              -- @AuditLog.action 또는 AUTH
    target      VARCHAR(100),              -- @AuditLog.target 또는 SESSION
    result      VARCHAR(20),               -- SUCCESS | FAILURE
    client_ip   VARCHAR(64),
    trace_id    VARCHAR(64),
    detail      VARCHAR(1000),
    elapsed_ms  BIGINT
);
CREATE INDEX IF NOT EXISTS idx_audit_time  ON audit_log(event_time);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_type  ON audit_log(event_type, event_time);
