-- Spring Cloud Task 5.0.1 — PostgreSQL 메타 스키마(공식 schema-postgresql.sql 기반, 운영 Flyway 선반영용).
-- 자동 DDL 은 끈다: spring.cloud.task.initialize-enabled=false (application.yml).
-- 표준 prefix(TASK_) 유지. 테이블/시퀀스/락 정의는 Spring Cloud Task 가 기대하는 형태와 동일해야 한다.

CREATE TABLE TASK_EXECUTION (
    TASK_EXECUTION_ID     BIGINT       NOT NULL PRIMARY KEY,
    START_TIME            TIMESTAMP    DEFAULT NULL,
    END_TIME              TIMESTAMP    DEFAULT NULL,
    TASK_NAME             VARCHAR(100),
    EXIT_CODE             INTEGER,
    EXIT_MESSAGE          VARCHAR(2500),
    ERROR_MESSAGE         VARCHAR(2500),
    LAST_UPDATED          TIMESTAMP,
    EXTERNAL_EXECUTION_ID VARCHAR(255),
    PARENT_EXECUTION_ID   BIGINT
);

CREATE TABLE TASK_EXECUTION_PARAMS (
    TASK_EXECUTION_ID BIGINT NOT NULL,
    TASK_PARAM        VARCHAR(2500),
    CONSTRAINT TASK_EXEC_PARAMS_FK FOREIGN KEY (TASK_EXECUTION_ID) REFERENCES TASK_EXECUTION (TASK_EXECUTION_ID)
);

-- 배치↔태스크 연결(JobExecution 이 어느 TaskExecution 에 속했는지).
CREATE TABLE TASK_TASK_BATCH (
    TASK_EXECUTION_ID BIGINT NOT NULL,
    JOB_EXECUTION_ID  BIGINT NOT NULL,
    CONSTRAINT TASK_EXEC_BATCH_FK FOREIGN KEY (TASK_EXECUTION_ID) REFERENCES TASK_EXECUTION (TASK_EXECUTION_ID)
);

CREATE SEQUENCE TASK_SEQ MAXVALUE 9223372036854775807 NO CYCLE;

-- single-instance-enabled=true 일 때 사용하는 분산 락.
CREATE TABLE TASK_LOCK (
    LOCK_KEY      CHAR(36)     NOT NULL,
    REGION        VARCHAR(100) NOT NULL,
    CLIENT_ID     CHAR(36),
    CREATED_DATE  TIMESTAMP    NOT NULL,
    EXPIRED_AFTER TIMESTAMP    NOT NULL,
    CONSTRAINT LOCK_PK PRIMARY KEY (LOCK_KEY, REGION)
);
