-- V3__rbac_metadata.sql
-- framework-security 의 RBAC 메타데이터 테이블(resources/roles/role_resources).
--
-- ⚠️ 왜 필요한가: framework.security.enabled=true 면 SecurityAutoConfiguration 이 SecurityMetadataService 빈을
--    무조건 생성하고, 그 생성자가 즉시 reload() → SecurityMapper.findAllResources() 를 호출한다(eager).
--    auth-server 는 동적 RBAC(DynamicAuthorizationManager)를 쓰지 않지만(자체 AS 체인 사용), 이 빈이 항상
--    만들어지므로 테이블이 없으면 기동 시 "Table RESOURCES not found" WARN 이 난다(비치명적이나 노이즈).
--    → 빈 테이블을 마련해 eager 로딩이 빈 결과로 통과하게 한다. (enabled=false 로 끄는 대신 이 방식을 쓴 이유:
--      LocalDemo 의 Authenticator 가 AuthAutoConfiguration→LoginService 를 트리거하는데, enabled=false 면
--      LoginService 의존 빈(JwtProvider/TokenStore 등)이 사라져 기동이 깨지기 때문.)
-- DDL 은 user-service 와 동일(H2·PostgreSQL 양립: GENERATED BY DEFAULT AS IDENTITY / TIMESTAMP).

CREATE TABLE IF NOT EXISTS roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    descr     VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS resources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_pattern VARCHAR(200) NOT NULL,
    http_method VARCHAR(10)  NOT NULL DEFAULT 'ALL',
    descr       VARCHAR(200),
    sort_order  INT DEFAULT 0,
    created_at  TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS role_resources (
    role_id     BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, resource_id)
);
