-- =====================================================================
-- V7 : auth-server 자체 사용자 저장소(authdb)
-- ---------------------------------------------------------------------
-- AS(OP)가 폼 로그인 사용자를 검증할 대상. DbAuthenticator(@Profile("!local"))가 조회한다.
-- ⚠️ 실 프로젝트는 이 테이블 대신 LDAP/AD/GPKI 등 자체 Authenticator 빈으로 교체할 수 있다
--    (framework-security 의 Authenticator SPI 한 개만 구현하면 됨 → @ConditionalOnMissingBean 로 자동 양보).
-- H2(PostgreSQL 모드) + PostgreSQL 양쪽 호환 DDL(ON CONFLICT/시퀀스 구문 회피).
-- =====================================================================
CREATE TABLE app_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id   VARCHAR(50)  NOT NULL UNIQUE,
    password   VARCHAR(200) NOT NULL,      -- DelegatingPasswordEncoder 포맷: {bcrypt}$2a$... (평문/{noop} 거부)
    name       VARCHAR(100) NOT NULL,
    role       VARCHAR(30)  NOT NULL DEFAULT 'USER',
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP
);

-- 데모/테스트 계정: tester / Test1234!  (BCrypt 해시, {bcrypt} 접두)
--   ⚠️ 운영 배포 시 이 seed 는 제거하고 실제 사용자/디렉터리 연동으로 대체할 것.
INSERT INTO app_user (login_id, password, name, role, enabled, created_at)
VALUES (
    'tester',
    '{bcrypt}$2b$10$APHJ9O6CEOEVioEv4IkIZ.b/qTBQ4uAIRzHrDyqQaJMKAekfASk2.',
    '테스터',
    'USER',
    TRUE,
    CURRENT_TIMESTAMP
);
