apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app.kubernetes.io/name: auth-server
    app.kubernetes.io/part-of: si-msa
    app.kubernetes.io/component: service
spec:
  selector:
    app.kubernetes.io/name: auth-server
  ports:
    - name: http
      port: 9000
      targetPort: http
