CREATE TABLE users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id  VARCHAR(50) NOT NULL UNIQUE,
    password  VARCHAR(200),
    name      VARCHAR(100),
    role      VARCHAR(20),
    created_at TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50)
);
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE, descr VARCHAR(200)
);
CREATE TABLE user_roles (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY (user_id, role_id));
CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_pattern VARCHAR(200) NOT NULL, http_method VARCHAR(10) NOT NULL DEFAULT 'ALL',
    descr VARCHAR(200), sort_order INT DEFAULT 0,
    created_at TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50)
);
CREATE TABLE role_resources (role_id BIGINT NOT NULL, resource_id BIGINT NOT NULL, PRIMARY KEY (role_id, resource_id));
CREATE TABLE menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT, name VARCHAR(100) NOT NULL, url VARCHAR(200), icon VARCHAR(50), sort_order INT DEFAULT 0,
    created_at TIMESTAMP, created_by VARCHAR(50), updated_at TIMESTAMP, updated_by VARCHAR(50)
);
CREATE TABLE role_menus (role_id BIGINT NOT NULL, menu_id BIGINT NOT NULL, PRIMARY KEY (role_id, menu_id));

INSERT INTO roles (id, role_name, descr) VALUES (1, 'ROLE_ADMIN', '관리자');
INSERT INTO roles (id, role_name, descr) VALUES (2, 'ROLE_USER',  '일반사용자');
