-- =====================================================================
-- 감사/접속 로그 테이블 (admin-service). framework.audit.store.type=jdbc 일 때 필요.
-- H2(PostgreSQL MODE) + PostgreSQL 양쪽 호환(IDENTITY 사용).
-- JdbcAuditEventSink 의 INSERT 컬럼과 1:1.
-- =====================================================================
CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time  TIMESTAMP    NOT NULL,
    event_type  VARCHAR(40)  NOT NULL,
    actor       VARCHAR(100),
    action      VARCHAR(100),
    target      VARCHAR(100),
    result      VARCHAR(20),
    client_ip   VARCHAR(64),
    trace_id    VARCHAR(64),
    detail      VARCHAR(1000),
    elapsed_ms  BIGINT
);
CREATE INDEX IF NOT EXISTS idx_audit_time  ON audit_log(event_time);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_type  ON audit_log(event_type, event_time);
