apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app.kubernetes.io/name: admin-service
    app.kubernetes.io/part-of: si-msa
    app.kubernetes.io/component: service
spec:
  selector:
    app.kubernetes.io/name: admin-service
  ports:
    - name: http
      port: 8081
      targetPort: http
