-- 정산 예제 도메인 테이블 + 동작 확인용 샘플 데이터.

CREATE TABLE raw_transaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id VARCHAR(40)    NOT NULL,
    amount      NUMERIC(18, 0) NOT NULL,
    status      VARCHAR(20)    NOT NULL, -- APPROVED / CANCELED / ...
    trade_date  DATE           NOT NULL,
    settled     BOOLEAN        NOT NULL DEFAULT FALSE
);

CREATE TABLE settlement_result (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id  VARCHAR(40)    NOT NULL,
    trade_date   DATE           NOT NULL,
    gross_amount NUMERIC(18, 0) NOT NULL,
    fee_amount   NUMERIC(18, 0) NOT NULL,
    net_amount   NUMERIC(18, 0) NOT NULL,
    created_at   TIMESTAMP      NOT NULL DEFAULT now()
);

-- 샘플: APPROVED 3건(정산 대상), CANCELED 1건(필터), 음수 1건(skip 유발).
INSERT INTO raw_transaction (merchant_id, amount, status, trade_date) VALUES
    ('M001', 100000, 'APPROVED', DATE '2026-06-07'),
    ('M001', 50000,  'APPROVED', DATE '2026-06-07'),
    ('M002', 230000, 'APPROVED', DATE '2026-06-07'),
    ('M002', 9999,   'CANCELED', DATE '2026-06-07'),
    ('M003', -100,   'APPROVED', DATE '2026-06-07');
